name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-dev \
            build-essential \
            git \
            autoconf \
            automake \
            zip \
            unzip \
            libltdl-dev \
            libssl-dev \
            libffi-dev \
            cmake \
            ninja-build \
            openjdk-17-jdk \
            libncurses5

      - name: Install Python Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build APK with Buildozer
        run: |
          # Buildozer сам скачает Android SDK/NDK и build-tools
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vless-hunter-apk
          path: bin/*.apk
